name: semantic release
description: 'check changelog and release action'

outputs:
  tag:
    description: generated tag
    value: ${{ steps.changelog.outputs.tag }}
  changelog:
    description: body of change log
    value: ${{ steps.changelog.outputs.clean_changelog }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3 # Checkout our working repository
  - name: Conventional Changelog Action
    id: changelog
    uses: TriPSs/conventional-changelog-action@v3
    with:
      github-token: ${{ secrets.github_token }}
      output-file: false
      pre-release: true
      skip-on-empty: false
      git-push: false
      skip-version-file: true
      skip-commit: true
  - name: Create Release # This action will create the actual release
    uses: actions/create-release@v1.1.4
    if: ${{ steps.changelog.outputs.skipped == 'false' }}
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
    with:
      tag_name: ${{ steps.changelog.outputs.tag }}
      release_name: ${{ steps.changelog.outputs.tag }}
      body: ${{ steps.changelog.outputs.clean_changelog }}
      prerelease: true
